language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python3 setup.py install"
# command to run tests
script:
  - "pylint ipavagrant ipa-vagrant-ci-*"
  - "pep8 ipavagrant/* ipa-vagrant-ci-* tests/*"
  - "py.test tests/ --verbose"
  
